# Generated by Django 4.0.1 on 2022-01-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
