# Generated by Django 4.0.1 on 2022-01-11 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('repository_link', models.URLField()),
                ('priority_order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Priority must be between 0 and 20'), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
